### ISSUE TITLE
Header image

### ISSUE THREAD

**Issue by pettykrooks** [matteomarchiori/w3csspress#1]
Hi friend, very well made and flexible Wordpress theme, specifying a header image breaks custom Google fonts and the header image doesn’t load, as far as I can tell. Otherwise working well for me.

**Comment by matteomarchiori** [comment]
Hi @pettykrooks , thank you really much for the notification.
I caused some bugs in middle versions of the theme because of changes in its structure.

The last version as of now should be working well (please, tell me if the problem is still there).
